# config for labeler action

documentation:
  - docs/**/*
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md

frontend:
  - apps/web/**/*

'team leads':
  - LICENSE.md
  - SECURITY.md
  - apps/docs/src/pages/legal/**/*

rust:
  - apps/desktop/**/*

ci:
  - .github/**/*

dependencies:
  - '**/package.json'
  - yarn.lock
  - .yarn/**/*
  - '**/Cargo.lock'
  - '**/Cargo.toml'
