# config for labeler action

documentation:
  - docs/**/*
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md

frontend:
  - apps/web/**/*

'team leads':
  - LICENSE.md
  - SECURITY.md
  - apps/docs/src/pages/legal/**/*

infrastructure:
  - .github/**/*
  - docker-compose.test.yml
  - docker-compose.yml
  - docker/**/*
  - '**/Dockerfile'

rust:
  - apps/desktop/**/*
