version: '3.8'

services:
  cockroach:
    image: cockroachdb/cockroach:latest-v22.2
    command: start-single-node --insecure
    ports:
      # postgres
      - 26257:26257
      # ui
      - 8081:8080
    volumes:
      - './dev/artifacts/database:/cockroach/cockroach-data'

  redis:
    image: redis
    ports:
      - '6379:6379'

  serverless-redis-http:
    ports:
      - '8079:80'
    image: hiett/serverless-redis-http:latest
    volumes:
      - ./dev/serverless-redis/tokens.json:/app/srh-config/tokens.json
